[package]
name = "howmanysmall/enumerator"
version = "1.0.0"
author = "howmanysmall"
dependencies_root="./src/enumerator"
content_root = "./src"
license = "MIT"

[dependencies]
t = { git = "https://github.com/osyrisrblx/t/" }